## HackerRank MySQL STUDENTS Problems ##
use 311_data;

SELECT *
FROM cases;


/* HERE IS THE SOLUTION TO THE HACKER RANK PROBLEM */
/* HERE IS THE SOLUTION TO THE HACKER RANK PROBLEM */
/* HERE IS THE SOLUTION TO THE HACKER RANK PROBLEM */
/* HERE IS THE SOLUTION TO THE HACKER RANK PROBLEM */